/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BoardsBoardIdRouteRouteImport } from './routes/boards/$boardId/route'
import { Route as BoardsBoardIdIndexRouteImport } from './routes/boards/$boardId/index'
import { Route as BoardsBoardIdCreateRouteImport } from './routes/boards/$boardId/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const BoardsBoardIdRouteRoute = BoardsBoardIdRouteRouteImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdIndexRoute = BoardsBoardIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BoardsBoardIdRouteRoute,
} as any)
const BoardsBoardIdCreateRoute = BoardsBoardIdCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => BoardsBoardIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/boards/$boardId': typeof BoardsBoardIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/': typeof AuthIndexRoute
  '/boards/$boardId/create': typeof BoardsBoardIdCreateRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth': typeof AuthIndexRoute
  '/boards/$boardId/create': typeof BoardsBoardIdCreateRoute
  '/boards/$boardId': typeof BoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/boards/$boardId': typeof BoardsBoardIdRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/': typeof AuthIndexRoute
  '/boards/$boardId/create': typeof BoardsBoardIdCreateRoute
  '/boards/$boardId/': typeof BoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boards/$boardId'
    | '/auth/login'
    | '/auth/'
    | '/boards/$boardId/create'
    | '/boards/$boardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth'
    | '/boards/$boardId/create'
    | '/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/boards/$boardId'
    | '/auth/login'
    | '/auth/'
    | '/boards/$boardId/create'
    | '/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  BoardsBoardIdRouteRoute: typeof BoardsBoardIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId/': {
      id: '/boards/$boardId/'
      path: '/'
      fullPath: '/boards/$boardId/'
      preLoaderRoute: typeof BoardsBoardIdIndexRouteImport
      parentRoute: typeof BoardsBoardIdRouteRoute
    }
    '/boards/$boardId/create': {
      id: '/boards/$boardId/create'
      path: '/create'
      fullPath: '/boards/$boardId/create'
      preLoaderRoute: typeof BoardsBoardIdCreateRouteImport
      parentRoute: typeof BoardsBoardIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface BoardsBoardIdRouteRouteChildren {
  BoardsBoardIdCreateRoute: typeof BoardsBoardIdCreateRoute
  BoardsBoardIdIndexRoute: typeof BoardsBoardIdIndexRoute
}

const BoardsBoardIdRouteRouteChildren: BoardsBoardIdRouteRouteChildren = {
  BoardsBoardIdCreateRoute: BoardsBoardIdCreateRoute,
  BoardsBoardIdIndexRoute: BoardsBoardIdIndexRoute,
}

const BoardsBoardIdRouteRouteWithChildren =
  BoardsBoardIdRouteRoute._addFileChildren(BoardsBoardIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  BoardsBoardIdRouteRoute: BoardsBoardIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
